baseURL = 'https://thilankal.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'nightfall'
publishDir = 'docs'


[params]
author = "Thilanka Liyanaarachchi"
user = "thilankal"
hostname = "github.io"

# [[params.social]]
# key = 0
# name = "blog"
# url = "/blog"

# [[params.social]]
# key = 1
# name = "about me"
# url = "/about"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/nuwan89"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/findthila"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/thilanka-liyanaarachchi-bb05532a/"

[[params.social]]
key = 3
name = "email"
url = "mailto:catchthila@gmail.com"